FROM halohub/halo:2.26.0
ENV TZ=Asia/Shanghai
ENV JAVA_OPTS="-Xms64m -Xmx192m -XX:+UseSerialGC -XX:ParallelGCThreads=1 -XX:CICompilerCount=2"
ENV HALO_SECURITY_REDIRECT=true
ENV SERVER_FORWARD=true
ENV LOGGING_LEVEL_IO_R2DBC_H2=ERROR
ENV LOGGING_ROOT_LEVEL=WARN
VOLUME ["/root/.halo2"]
EXPOSE 8090
